// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.2
// source: order/order_event.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单支付成功事件
type OnPaymentSuccess struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	OrderId       int64                   `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Products      []*ProductInventoryItem `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnPaymentSuccess) Reset() {
	*x = OnPaymentSuccess{}
	mi := &file_order_order_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnPaymentSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPaymentSuccess) ProtoMessage() {}

func (x *OnPaymentSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPaymentSuccess.ProtoReflect.Descriptor instead.
func (*OnPaymentSuccess) Descriptor() ([]byte, []int) {
	return file_order_order_event_proto_rawDescGZIP(), []int{0}
}

func (x *OnPaymentSuccess) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OnPaymentSuccess) GetProducts() []*ProductInventoryItem {
	if x != nil {
		return x.Products
	}
	return nil
}

// 订单涉及的商品库存
type ProductInventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductNum    int64                  `protobuf:"varint,2,opt,name=product_num,json=productNum,proto3" json:"product_num,omitempty"`
	ProductSizeId int64                  `protobuf:"varint,3,opt,name=product_size_id,json=productSizeId,proto3" json:"product_size_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInventoryItem) Reset() {
	*x = ProductInventoryItem{}
	mi := &file_order_order_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInventoryItem) ProtoMessage() {}

func (x *ProductInventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInventoryItem.ProtoReflect.Descriptor instead.
func (*ProductInventoryItem) Descriptor() ([]byte, []int) {
	return file_order_order_event_proto_rawDescGZIP(), []int{1}
}

func (x *ProductInventoryItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductInventoryItem) GetProductNum() int64 {
	if x != nil {
		return x.ProductNum
	}
	return 0
}

func (x *ProductInventoryItem) GetProductSizeId() int64 {
	if x != nil {
		return x.ProductSizeId
	}
	return 0
}

var File_order_order_event_proto protoreflect.FileDescriptor

const file_order_order_event_proto_rawDesc = "" +
	"\n" +
	"\x17order/order_event.proto\x12\vorder.event\"k\n" +
	"\x10OnPaymentSuccess\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12=\n" +
	"\bproducts\x18\x02 \x03(\v2!.order.event.ProductInventoryItemR\bproducts\"~\n" +
	"\x14ProductInventoryItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vproduct_num\x18\x02 \x01(\x03R\n" +
	"productNum\x12&\n" +
	"\x0fproduct_size_id\x18\x03 \x01(\x03R\rproductSizeIdB\x1fZ\x1d./internal/domain/event/orderb\x06proto3"

var (
	file_order_order_event_proto_rawDescOnce sync.Once
	file_order_order_event_proto_rawDescData []byte
)

func file_order_order_event_proto_rawDescGZIP() []byte {
	file_order_order_event_proto_rawDescOnce.Do(func() {
		file_order_order_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_event_proto_rawDesc), len(file_order_order_event_proto_rawDesc)))
	})
	return file_order_order_event_proto_rawDescData
}

var file_order_order_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_order_event_proto_goTypes = []any{
	(*OnPaymentSuccess)(nil),     // 0: order.event.OnPaymentSuccess
	(*ProductInventoryItem)(nil), // 1: order.event.ProductInventoryItem
}
var file_order_order_event_proto_depIdxs = []int32{
	1, // 0: order.event.OnPaymentSuccess.products:type_name -> order.event.ProductInventoryItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_order_event_proto_init() }
func file_order_order_event_proto_init() {
	if File_order_order_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_event_proto_rawDesc), len(file_order_order_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_order_event_proto_goTypes,
		DependencyIndexes: file_order_order_event_proto_depIdxs,
		MessageInfos:      file_order_order_event_proto_msgTypes,
	}.Build()
	File_order_order_event_proto = out.File
	file_order_order_event_proto_goTypes = nil
	file_order_order_event_proto_depIdxs = nil
}
