// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.2
// source: order/order_event.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单支付成功事件
type OnPaymentSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	OrderDetails  []*OrderDetail         `protobuf:"bytes,2,rep,name=OrderDetails,proto3" json:"OrderDetails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnPaymentSuccess) Reset() {
	*x = OnPaymentSuccess{}
	mi := &file_order_order_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnPaymentSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPaymentSuccess) ProtoMessage() {}

func (x *OnPaymentSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPaymentSuccess.ProtoReflect.Descriptor instead.
func (*OnPaymentSuccess) Descriptor() ([]byte, []int) {
	return file_order_order_event_proto_rawDescGZIP(), []int{0}
}

func (x *OnPaymentSuccess) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OnPaymentSuccess) GetOrderDetails() []*OrderDetail {
	if x != nil {
		return x.OrderDetails
	}
	return nil
}

// 订单-商品Sku
type OrderDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_order_order_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_order_order_event_proto_rawDescGZIP(), []int{1}
}

func (x *OrderDetail) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderDetail) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *OrderDetail) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_order_order_event_proto protoreflect.FileDescriptor

const file_order_order_event_proto_rawDesc = "" +
	"\n" +
	"\x17order/order_event.proto\x12\vorder.event\"j\n" +
	"\x10OnPaymentSuccess\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12<\n" +
	"\fOrderDetails\x18\x02 \x03(\v2\x18.order.event.OrderDetailR\fOrderDetails\"_\n" +
	"\vOrderDetail\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x03R\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantityB\x1fZ\x1d./internal/domain/event/orderb\x06proto3"

var (
	file_order_order_event_proto_rawDescOnce sync.Once
	file_order_order_event_proto_rawDescData []byte
)

func file_order_order_event_proto_rawDescGZIP() []byte {
	file_order_order_event_proto_rawDescOnce.Do(func() {
		file_order_order_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_event_proto_rawDesc), len(file_order_order_event_proto_rawDesc)))
	})
	return file_order_order_event_proto_rawDescData
}

var file_order_order_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_order_event_proto_goTypes = []any{
	(*OnPaymentSuccess)(nil), // 0: order.event.OnPaymentSuccess
	(*OrderDetail)(nil),      // 1: order.event.OrderDetail
}
var file_order_order_event_proto_depIdxs = []int32{
	1, // 0: order.event.OnPaymentSuccess.OrderDetails:type_name -> order.event.OrderDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_order_event_proto_init() }
func file_order_order_event_proto_init() {
	if File_order_order_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_event_proto_rawDesc), len(file_order_order_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_order_event_proto_goTypes,
		DependencyIndexes: file_order_order_event_proto_depIdxs,
		MessageInfos:      file_order_order_event_proto_msgTypes,
	}.Build()
	File_order_order_event_proto = out.File
	file_order_order_event_proto_goTypes = nil
	file_order_order_event_proto_depIdxs = nil
}
