// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.2
// source: proto/base_event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基础事件
type BaseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_proto_base_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_base_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEvent.ProtoReflect.Descriptor instead.
func (*BaseEvent) Descriptor() ([]byte, []int) {
	return file_proto_base_event_proto_rawDescGZIP(), []int{0}
}

func (x *BaseEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BaseEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BaseEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_base_event_proto protoreflect.FileDescriptor

const file_proto_base_event_proto_rawDesc = "" +
	"\n" +
	"\x16proto/base_event.proto\x12\x06common\"b\n" +
	"\tBaseEvent\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayloadB\x19Z\x17./internal/domain/eventb\x06proto3"

var (
	file_proto_base_event_proto_rawDescOnce sync.Once
	file_proto_base_event_proto_rawDescData []byte
)

func file_proto_base_event_proto_rawDescGZIP() []byte {
	file_proto_base_event_proto_rawDescOnce.Do(func() {
		file_proto_base_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_base_event_proto_rawDesc), len(file_proto_base_event_proto_rawDesc)))
	})
	return file_proto_base_event_proto_rawDescData
}

var file_proto_base_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_base_event_proto_goTypes = []any{
	(*BaseEvent)(nil), // 0: common.BaseEvent
}
var file_proto_base_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_base_event_proto_init() }
func file_proto_base_event_proto_init() {
	if File_proto_base_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_base_event_proto_rawDesc), len(file_proto_base_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_base_event_proto_goTypes,
		DependencyIndexes: file_proto_base_event_proto_depIdxs,
		MessageInfos:      file_proto_base_event_proto_msgTypes,
	}.Build()
	File_proto_base_event_proto = out.File
	file_proto_base_event_proto_goTypes = nil
	file_proto_base_event_proto_depIdxs = nil
}
