// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product/product.proto

package product

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Product service

func NewProductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Product service

type ProductService interface {
	AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ResponseProduct, error)
	GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, opts ...client.CallOption) (*GetProductSkuDetailResponse, error)
	CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, opts ...client.CallOption) (*CheckSkuInventoryThresholdResponse, error)
	GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, opts ...client.CallOption) (*GetSkuStockBySkuNoResponse, error)
	CreateRestockApply(ctx context.Context, in *CreateRestockApplyRequest, opts ...client.CallOption) (*CreateRestockApplyResponse, error)
	GetSkuSalesVolume(ctx context.Context, in *GetSkuSalesVolumeRequest, opts ...client.CallOption) (*GetSkuSalesVolumeResponse, error)
	GetSupplierInfo(ctx context.Context, in *GetSupplierInfoRequest, opts ...client.CallOption) (*GetSupplierInfoResponse, error)
	GetRestockApplyInfo(ctx context.Context, in *GetRestockApplyInfoRequest, opts ...client.CallOption) (*GetRestockApplyInfoResponse, error)
	GetSkuDailySales(ctx context.Context, in *GetSkuDailySalesRequest, opts ...client.CallOption) (*GetSkuDailySalesResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ResponseProduct, error) {
	req := c.c.NewRequest(c.name, "Product.AddProduct", in)
	out := new(ResponseProduct)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, opts ...client.CallOption) (*GetProductSkuDetailResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetProductSkuDetail", in)
	out := new(GetProductSkuDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, opts ...client.CallOption) (*CheckSkuInventoryThresholdResponse, error) {
	req := c.c.NewRequest(c.name, "Product.CheckSkuInventoryThreshold", in)
	out := new(CheckSkuInventoryThresholdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, opts ...client.CallOption) (*GetSkuStockBySkuNoResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetSkuStockBySkuNo", in)
	out := new(GetSkuStockBySkuNoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) CreateRestockApply(ctx context.Context, in *CreateRestockApplyRequest, opts ...client.CallOption) (*CreateRestockApplyResponse, error) {
	req := c.c.NewRequest(c.name, "Product.CreateRestockApply", in)
	out := new(CreateRestockApplyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetSkuSalesVolume(ctx context.Context, in *GetSkuSalesVolumeRequest, opts ...client.CallOption) (*GetSkuSalesVolumeResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetSkuSalesVolume", in)
	out := new(GetSkuSalesVolumeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetSupplierInfo(ctx context.Context, in *GetSupplierInfoRequest, opts ...client.CallOption) (*GetSupplierInfoResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetSupplierInfo", in)
	out := new(GetSupplierInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetRestockApplyInfo(ctx context.Context, in *GetRestockApplyInfoRequest, opts ...client.CallOption) (*GetRestockApplyInfoResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetRestockApplyInfo", in)
	out := new(GetRestockApplyInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetSkuDailySales(ctx context.Context, in *GetSkuDailySalesRequest, opts ...client.CallOption) (*GetSkuDailySalesResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetSkuDailySales", in)
	out := new(GetSkuDailySalesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Product service

type ProductHandler interface {
	AddProduct(context.Context, *ProductInfo, *ResponseProduct) error
	GetProductSkuDetail(context.Context, *GetProductSkuDetailRequest, *GetProductSkuDetailResponse) error
	CheckSkuInventoryThreshold(context.Context, *CheckSkuInventoryThresholdRequest, *CheckSkuInventoryThresholdResponse) error
	GetSkuStockBySkuNo(context.Context, *GetSkuStockBySkuNoRequest, *GetSkuStockBySkuNoResponse) error
	CreateRestockApply(context.Context, *CreateRestockApplyRequest, *CreateRestockApplyResponse) error
	GetSkuSalesVolume(context.Context, *GetSkuSalesVolumeRequest, *GetSkuSalesVolumeResponse) error
	GetSupplierInfo(context.Context, *GetSupplierInfoRequest, *GetSupplierInfoResponse) error
	GetRestockApplyInfo(context.Context, *GetRestockApplyInfoRequest, *GetRestockApplyInfoResponse) error
	GetSkuDailySales(context.Context, *GetSkuDailySalesRequest, *GetSkuDailySalesResponse) error
}

func RegisterProductHandler(s server.Server, hdlr ProductHandler, opts ...server.HandlerOption) error {
	type product interface {
		AddProduct(ctx context.Context, in *ProductInfo, out *ResponseProduct) error
		GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, out *GetProductSkuDetailResponse) error
		CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, out *CheckSkuInventoryThresholdResponse) error
		GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, out *GetSkuStockBySkuNoResponse) error
		CreateRestockApply(ctx context.Context, in *CreateRestockApplyRequest, out *CreateRestockApplyResponse) error
		GetSkuSalesVolume(ctx context.Context, in *GetSkuSalesVolumeRequest, out *GetSkuSalesVolumeResponse) error
		GetSupplierInfo(ctx context.Context, in *GetSupplierInfoRequest, out *GetSupplierInfoResponse) error
		GetRestockApplyInfo(ctx context.Context, in *GetRestockApplyInfoRequest, out *GetRestockApplyInfoResponse) error
		GetSkuDailySales(ctx context.Context, in *GetSkuDailySalesRequest, out *GetSkuDailySalesResponse) error
	}
	type Product struct {
		product
	}
	h := &productHandler{hdlr}
	return s.Handle(s.NewHandler(&Product{h}, opts...))
}

type productHandler struct {
	ProductHandler
}

func (h *productHandler) AddProduct(ctx context.Context, in *ProductInfo, out *ResponseProduct) error {
	return h.ProductHandler.AddProduct(ctx, in, out)
}

func (h *productHandler) GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, out *GetProductSkuDetailResponse) error {
	return h.ProductHandler.GetProductSkuDetail(ctx, in, out)
}

func (h *productHandler) CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, out *CheckSkuInventoryThresholdResponse) error {
	return h.ProductHandler.CheckSkuInventoryThreshold(ctx, in, out)
}

func (h *productHandler) GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, out *GetSkuStockBySkuNoResponse) error {
	return h.ProductHandler.GetSkuStockBySkuNo(ctx, in, out)
}

func (h *productHandler) CreateRestockApply(ctx context.Context, in *CreateRestockApplyRequest, out *CreateRestockApplyResponse) error {
	return h.ProductHandler.CreateRestockApply(ctx, in, out)
}

func (h *productHandler) GetSkuSalesVolume(ctx context.Context, in *GetSkuSalesVolumeRequest, out *GetSkuSalesVolumeResponse) error {
	return h.ProductHandler.GetSkuSalesVolume(ctx, in, out)
}

func (h *productHandler) GetSupplierInfo(ctx context.Context, in *GetSupplierInfoRequest, out *GetSupplierInfoResponse) error {
	return h.ProductHandler.GetSupplierInfo(ctx, in, out)
}

func (h *productHandler) GetRestockApplyInfo(ctx context.Context, in *GetRestockApplyInfoRequest, out *GetRestockApplyInfoResponse) error {
	return h.ProductHandler.GetRestockApplyInfo(ctx, in, out)
}

func (h *productHandler) GetSkuDailySales(ctx context.Context, in *GetSkuDailySalesRequest, out *GetSkuDailySalesResponse) error {
	return h.ProductHandler.GetSkuDailySales(ctx, in, out)
}
