// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product/product.proto

package product

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Product service

func NewProductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Product service

type ProductService interface {
	AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ResponseProduct, error)
	GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, opts ...client.CallOption) (*GetProductSkuDetailResponse, error)
	CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, opts ...client.CallOption) (*CheckSkuInventoryThresholdResponse, error)
	GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, opts ...client.CallOption) (*GetSkuStockBySkuNoResponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ResponseProduct, error) {
	req := c.c.NewRequest(c.name, "Product.AddProduct", in)
	out := new(ResponseProduct)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, opts ...client.CallOption) (*GetProductSkuDetailResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetProductSkuDetail", in)
	out := new(GetProductSkuDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, opts ...client.CallOption) (*CheckSkuInventoryThresholdResponse, error) {
	req := c.c.NewRequest(c.name, "Product.CheckSkuInventoryThreshold", in)
	out := new(CheckSkuInventoryThresholdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, opts ...client.CallOption) (*GetSkuStockBySkuNoResponse, error) {
	req := c.c.NewRequest(c.name, "Product.GetSkuStockBySkuNo", in)
	out := new(GetSkuStockBySkuNoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Product service

type ProductHandler interface {
	AddProduct(context.Context, *ProductInfo, *ResponseProduct) error
	GetProductSkuDetail(context.Context, *GetProductSkuDetailRequest, *GetProductSkuDetailResponse) error
	CheckSkuInventoryThreshold(context.Context, *CheckSkuInventoryThresholdRequest, *CheckSkuInventoryThresholdResponse) error
	GetSkuStockBySkuNo(context.Context, *GetSkuStockBySkuNoRequest, *GetSkuStockBySkuNoResponse) error
}

func RegisterProductHandler(s server.Server, hdlr ProductHandler, opts ...server.HandlerOption) error {
	type product interface {
		AddProduct(ctx context.Context, in *ProductInfo, out *ResponseProduct) error
		GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, out *GetProductSkuDetailResponse) error
		CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, out *CheckSkuInventoryThresholdResponse) error
		GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, out *GetSkuStockBySkuNoResponse) error
	}
	type Product struct {
		product
	}
	h := &productHandler{hdlr}
	return s.Handle(s.NewHandler(&Product{h}, opts...))
}

type productHandler struct {
	ProductHandler
}

func (h *productHandler) AddProduct(ctx context.Context, in *ProductInfo, out *ResponseProduct) error {
	return h.ProductHandler.AddProduct(ctx, in, out)
}

func (h *productHandler) GetProductSkuDetail(ctx context.Context, in *GetProductSkuDetailRequest, out *GetProductSkuDetailResponse) error {
	return h.ProductHandler.GetProductSkuDetail(ctx, in, out)
}

func (h *productHandler) CheckSkuInventoryThreshold(ctx context.Context, in *CheckSkuInventoryThresholdRequest, out *CheckSkuInventoryThresholdResponse) error {
	return h.ProductHandler.CheckSkuInventoryThreshold(ctx, in, out)
}

func (h *productHandler) GetSkuStockBySkuNo(ctx context.Context, in *GetSkuStockBySkuNoRequest, out *GetSkuStockBySkuNoResponse) error {
	return h.ProductHandler.GetSkuStockBySkuNo(ctx, in, out)
}
