// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.2
// source: proto/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName        string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductSku         string                 `protobuf:"bytes,3,opt,name=product_sku,json=productSku,proto3" json:"product_sku,omitempty"`
	ProductPrice       float64                `protobuf:"fixed64,4,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	ProductDescription string                 `protobuf:"bytes,5,opt,name=product_description,json=productDescription,proto3" json:"product_description,omitempty"`
	ProductCategoryId  int64                  `protobuf:"varint,6,opt,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductInfo) GetProductSku() string {
	if x != nil {
		return x.ProductSku
	}
	return ""
}

func (x *ProductInfo) GetProductPrice() float64 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

func (x *ProductInfo) GetProductDescription() string {
	if x != nil {
		return x.ProductDescription
	}
	return ""
}

func (x *ProductInfo) GetProductCategoryId() int64 {
	if x != nil {
		return x.ProductCategoryId
	}
	return 0
}

type ResponseProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseProduct) Reset() {
	*x = ResponseProduct{}
	mi := &file_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseProduct) ProtoMessage() {}

func (x *ResponseProduct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseProduct.ProtoReflect.Descriptor instead.
func (*ResponseProduct) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseProduct) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type OrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Products      []*ProductInvetoryItem `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailReq) Reset() {
	*x = OrderDetailReq{}
	mi := &file_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailReq) ProtoMessage() {}

func (x *OrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailReq.ProtoReflect.Descriptor instead.
func (*OrderDetailReq) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDetailReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderDetailReq) GetProducts() []*ProductInvetoryItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductInvetoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductNum    int64                  `protobuf:"varint,2,opt,name=product_num,json=productNum,proto3" json:"product_num,omitempty"`
	ProductSizeId int64                  `protobuf:"varint,3,opt,name=product_size_id,json=productSizeId,proto3" json:"product_size_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInvetoryItem) Reset() {
	*x = ProductInvetoryItem{}
	mi := &file_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInvetoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInvetoryItem) ProtoMessage() {}

func (x *ProductInvetoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInvetoryItem.ProtoReflect.Descriptor instead.
func (*ProductInvetoryItem) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductInvetoryItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductInvetoryItem) GetProductNum() int64 {
	if x != nil {
		return x.ProductNum
	}
	return 0
}

func (x *ProductInvetoryItem) GetProductSizeId() int64 {
	if x != nil {
		return x.ProductSizeId
	}
	return 0
}

type OrderProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProductResp) Reset() {
	*x = OrderProductResp{}
	mi := &file_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductResp) ProtoMessage() {}

func (x *OrderProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductResp.ProtoReflect.Descriptor instead.
func (*OrderProductResp) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *OrderProductResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderProductResp) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

var File_proto_product_product_proto protoreflect.FileDescriptor

const file_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/product.proto\x12\x10go.micro.service\"\xe7\x01\n" +
	"\vProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1f\n" +
	"\vproduct_sku\x18\x03 \x01(\tR\n" +
	"productSku\x12#\n" +
	"\rproduct_price\x18\x04 \x01(\x01R\fproductPrice\x12/\n" +
	"\x13product_description\x18\x05 \x01(\tR\x12productDescription\x12.\n" +
	"\x13product_category_id\x18\x06 \x01(\x03R\x11productCategoryId\"0\n" +
	"\x0fResponseProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"n\n" +
	"\x0eOrderDetailReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12A\n" +
	"\bproducts\x18\x02 \x03(\v2%.go.micro.service.ProductInvetoryItemR\bproducts\"}\n" +
	"\x13ProductInvetoryItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1f\n" +
	"\vproduct_num\x18\x02 \x01(\x03R\n" +
	"productNum\x12&\n" +
	"\x0fproduct_size_id\x18\x03 \x01(\x03R\rproductSizeId\"M\n" +
	"\x10OrderProductResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1e\n" +
	"\n" +
	"StatusCode\x18\x02 \x01(\tR\n" +
	"StatusCode2\x95\x02\n" +
	"\aProduct\x12P\n" +
	"\n" +
	"AddProduct\x12\x1d.go.micro.service.ProductInfo\x1a!.go.micro.service.ResponseProduct\"\x00\x12X\n" +
	"\x0eDeductInvetory\x12 .go.micro.service.OrderDetailReq\x1a\".go.micro.service.OrderProductResp\"\x00\x12^\n" +
	"\x14DeductInvetoryRevert\x12 .go.micro.service.OrderDetailReq\x1a\".go.micro.service.OrderProductResp\"\x00B\x11Z\x0f./proto/productb\x06proto3"

var (
	file_proto_product_product_proto_rawDescOnce sync.Once
	file_proto_product_product_proto_rawDescData []byte
)

func file_proto_product_product_proto_rawDescGZIP() []byte {
	file_proto_product_product_proto_rawDescOnce.Do(func() {
		file_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)))
	})
	return file_proto_product_product_proto_rawDescData
}

var file_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_product_product_proto_goTypes = []any{
	(*ProductInfo)(nil),         // 0: go.micro.service.ProductInfo
	(*ResponseProduct)(nil),     // 1: go.micro.service.ResponseProduct
	(*OrderDetailReq)(nil),      // 2: go.micro.service.OrderDetailReq
	(*ProductInvetoryItem)(nil), // 3: go.micro.service.ProductInvetoryItem
	(*OrderProductResp)(nil),    // 4: go.micro.service.OrderProductResp
}
var file_proto_product_product_proto_depIdxs = []int32{
	3, // 0: go.micro.service.OrderDetailReq.products:type_name -> go.micro.service.ProductInvetoryItem
	0, // 1: go.micro.service.Product.AddProduct:input_type -> go.micro.service.ProductInfo
	2, // 2: go.micro.service.Product.DeductInvetory:input_type -> go.micro.service.OrderDetailReq
	2, // 3: go.micro.service.Product.DeductInvetoryRevert:input_type -> go.micro.service.OrderDetailReq
	1, // 4: go.micro.service.Product.AddProduct:output_type -> go.micro.service.ResponseProduct
	4, // 5: go.micro.service.Product.DeductInvetory:output_type -> go.micro.service.OrderProductResp
	4, // 6: go.micro.service.Product.DeductInvetoryRevert:output_type -> go.micro.service.OrderProductResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_product_product_proto_init() }
func file_proto_product_product_proto_init() {
	if File_proto_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_product_proto_goTypes,
		DependencyIndexes: file_proto_product_product_proto_depIdxs,
		MessageInfos:      file_proto_product_product_proto_msgTypes,
	}.Build()
	File_proto_product_product_proto = out.File
	file_proto_product_product_proto_goTypes = nil
	file_proto_product_product_proto_depIdxs = nil
}
