// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/product/product.proto

package product

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Product service

func NewProductEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Product service

type ProductService interface {
	AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ResponseProduct, error)
	DeductInvetory(ctx context.Context, in *OrderDetailReq, opts ...client.CallOption) (*OrderProductResp, error)
	DeductInvetoryRevert(ctx context.Context, in *OrderDetailReq, opts ...client.CallOption) (*OrderProductResp, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) AddProduct(ctx context.Context, in *ProductInfo, opts ...client.CallOption) (*ResponseProduct, error) {
	req := c.c.NewRequest(c.name, "Product.AddProduct", in)
	out := new(ResponseProduct)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) DeductInvetory(ctx context.Context, in *OrderDetailReq, opts ...client.CallOption) (*OrderProductResp, error) {
	req := c.c.NewRequest(c.name, "Product.DeductInvetory", in)
	out := new(OrderProductResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productService) DeductInvetoryRevert(ctx context.Context, in *OrderDetailReq, opts ...client.CallOption) (*OrderProductResp, error) {
	req := c.c.NewRequest(c.name, "Product.DeductInvetoryRevert", in)
	out := new(OrderProductResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Product service

type ProductHandler interface {
	AddProduct(context.Context, *ProductInfo, *ResponseProduct) error
	DeductInvetory(context.Context, *OrderDetailReq, *OrderProductResp) error
	DeductInvetoryRevert(context.Context, *OrderDetailReq, *OrderProductResp) error
}

func RegisterProductHandler(s server.Server, hdlr ProductHandler, opts ...server.HandlerOption) error {
	type product interface {
		AddProduct(ctx context.Context, in *ProductInfo, out *ResponseProduct) error
		DeductInvetory(ctx context.Context, in *OrderDetailReq, out *OrderProductResp) error
		DeductInvetoryRevert(ctx context.Context, in *OrderDetailReq, out *OrderProductResp) error
	}
	type Product struct {
		product
	}
	h := &productHandler{hdlr}
	return s.Handle(s.NewHandler(&Product{h}, opts...))
}

type productHandler struct {
	ProductHandler
}

func (h *productHandler) AddProduct(ctx context.Context, in *ProductInfo, out *ResponseProduct) error {
	return h.ProductHandler.AddProduct(ctx, in, out)
}

func (h *productHandler) DeductInvetory(ctx context.Context, in *OrderDetailReq, out *OrderProductResp) error {
	return h.ProductHandler.DeductInvetory(ctx, in, out)
}

func (h *productHandler) DeductInvetoryRevert(ctx context.Context, in *OrderDetailReq, out *OrderProductResp) error {
	return h.ProductHandler.DeductInvetoryRevert(ctx, in, out)
}
