// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.2
// source: proto/product/product_event.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 库存扣减成功
type OnInventoryDeductSuccess struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	OrderId       int64                       `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Products      []*ProductInventoryItem     `protobuf:"bytes,2,rep,name=Products,proto3" json:"Products,omitempty"`
	ProductSizes  []*ProductSizeInventoryItem `protobuf:"bytes,3,rep,name=ProductSizes,proto3" json:"ProductSizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnInventoryDeductSuccess) Reset() {
	*x = OnInventoryDeductSuccess{}
	mi := &file_proto_product_product_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnInventoryDeductSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnInventoryDeductSuccess) ProtoMessage() {}

func (x *OnInventoryDeductSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnInventoryDeductSuccess.ProtoReflect.Descriptor instead.
func (*OnInventoryDeductSuccess) Descriptor() ([]byte, []int) {
	return file_proto_product_product_event_proto_rawDescGZIP(), []int{0}
}

func (x *OnInventoryDeductSuccess) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OnInventoryDeductSuccess) GetProducts() []*ProductInventoryItem {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *OnInventoryDeductSuccess) GetProductSizes() []*ProductSizeInventoryItem {
	if x != nil {
		return x.ProductSizes
	}
	return nil
}

type ProductInventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInventoryItem) Reset() {
	*x = ProductInventoryItem{}
	mi := &file_proto_product_product_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInventoryItem) ProtoMessage() {}

func (x *ProductInventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInventoryItem.ProtoReflect.Descriptor instead.
func (*ProductInventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_product_product_event_proto_rawDescGZIP(), []int{1}
}

func (x *ProductInventoryItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductInventoryItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProductSizeInventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductSizeInventoryItem) Reset() {
	*x = ProductSizeInventoryItem{}
	mi := &file_proto_product_product_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductSizeInventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductSizeInventoryItem) ProtoMessage() {}

func (x *ProductSizeInventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductSizeInventoryItem.ProtoReflect.Descriptor instead.
func (*ProductSizeInventoryItem) Descriptor() ([]byte, []int) {
	return file_proto_product_product_event_proto_rawDescGZIP(), []int{2}
}

func (x *ProductSizeInventoryItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductSizeInventoryItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_product_product_event_proto protoreflect.FileDescriptor

const file_proto_product_product_event_proto_rawDesc = "" +
	"\n" +
	"!proto/product/product_event.proto\x12\rproduct.event\"\xc2\x01\n" +
	"\x18OnInventoryDeductSuccess\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12?\n" +
	"\bProducts\x18\x02 \x03(\v2#.product.event.ProductInventoryItemR\bProducts\x12K\n" +
	"\fProductSizes\x18\x03 \x03(\v2'.product.event.ProductSizeInventoryItemR\fProductSizes\"<\n" +
	"\x14ProductInventoryItem\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x03R\x05Count\"@\n" +
	"\x18ProductSizeInventoryItem\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x03R\x05CountB!Z\x1f./internal/domain/event/productb\x06proto3"

var (
	file_proto_product_product_event_proto_rawDescOnce sync.Once
	file_proto_product_product_event_proto_rawDescData []byte
)

func file_proto_product_product_event_proto_rawDescGZIP() []byte {
	file_proto_product_product_event_proto_rawDescOnce.Do(func() {
		file_proto_product_product_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_event_proto_rawDesc), len(file_proto_product_product_event_proto_rawDesc)))
	})
	return file_proto_product_product_event_proto_rawDescData
}

var file_proto_product_product_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_product_product_event_proto_goTypes = []any{
	(*OnInventoryDeductSuccess)(nil), // 0: product.event.OnInventoryDeductSuccess
	(*ProductInventoryItem)(nil),     // 1: product.event.ProductInventoryItem
	(*ProductSizeInventoryItem)(nil), // 2: product.event.ProductSizeInventoryItem
}
var file_proto_product_product_event_proto_depIdxs = []int32{
	1, // 0: product.event.OnInventoryDeductSuccess.Products:type_name -> product.event.ProductInventoryItem
	2, // 1: product.event.OnInventoryDeductSuccess.ProductSizes:type_name -> product.event.ProductSizeInventoryItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_product_event_proto_init() }
func file_proto_product_product_event_proto_init() {
	if File_proto_product_product_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_event_proto_rawDesc), len(file_proto_product_product_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_product_product_event_proto_goTypes,
		DependencyIndexes: file_proto_product_product_event_proto_depIdxs,
		MessageInfos:      file_proto_product_product_event_proto_msgTypes,
	}.Build()
	File_proto_product_product_event_proto = out.File
	file_proto_product_product_event_proto_goTypes = nil
	file_proto_product_product_event_proto_depIdxs = nil
}
