// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.2
// source: proto/product/product_event.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 库存扣减成功
type OnInventoryDeductSuccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Sku           []*SkuInfo             `protobuf:"bytes,2,rep,name=Sku,proto3" json:"Sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnInventoryDeductSuccess) Reset() {
	*x = OnInventoryDeductSuccess{}
	mi := &file_proto_product_product_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnInventoryDeductSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnInventoryDeductSuccess) ProtoMessage() {}

func (x *OnInventoryDeductSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnInventoryDeductSuccess.ProtoReflect.Descriptor instead.
func (*OnInventoryDeductSuccess) Descriptor() ([]byte, []int) {
	return file_proto_product_product_event_proto_rawDescGZIP(), []int{0}
}

func (x *OnInventoryDeductSuccess) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OnInventoryDeductSuccess) GetSku() []*SkuInfo {
	if x != nil {
		return x.Sku
	}
	return nil
}

type SkuInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Stock         uint32                 `protobuf:"varint,3,opt,name=Stock,proto3" json:"Stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuInfo) Reset() {
	*x = SkuInfo{}
	mi := &file_proto_product_product_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInfo) ProtoMessage() {}

func (x *SkuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInfo.ProtoReflect.Descriptor instead.
func (*SkuInfo) Descriptor() ([]byte, []int) {
	return file_proto_product_product_event_proto_rawDescGZIP(), []int{1}
}

func (x *SkuInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SkuInfo) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SkuInfo) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_proto_product_product_event_proto protoreflect.FileDescriptor

const file_proto_product_product_event_proto_rawDesc = "" +
	"\n" +
	"!proto/product/product_event.proto\x12\rproduct.event\"^\n" +
	"\x18OnInventoryDeductSuccess\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12(\n" +
	"\x03Sku\x18\x02 \x03(\v2\x16.product.event.SkuInfoR\x03Sku\"K\n" +
	"\aSkuInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\rR\bQuantity\x12\x14\n" +
	"\x05Stock\x18\x03 \x01(\rR\x05StockB!Z\x1f./internal/domain/event/productb\x06proto3"

var (
	file_proto_product_product_event_proto_rawDescOnce sync.Once
	file_proto_product_product_event_proto_rawDescData []byte
)

func file_proto_product_product_event_proto_rawDescGZIP() []byte {
	file_proto_product_product_event_proto_rawDescOnce.Do(func() {
		file_proto_product_product_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_event_proto_rawDesc), len(file_proto_product_product_event_proto_rawDesc)))
	})
	return file_proto_product_product_event_proto_rawDescData
}

var file_proto_product_product_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_product_product_event_proto_goTypes = []any{
	(*OnInventoryDeductSuccess)(nil), // 0: product.event.OnInventoryDeductSuccess
	(*SkuInfo)(nil),                  // 1: product.event.SkuInfo
}
var file_proto_product_product_event_proto_depIdxs = []int32{
	1, // 0: product.event.OnInventoryDeductSuccess.Sku:type_name -> product.event.SkuInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_product_product_event_proto_init() }
func file_proto_product_product_event_proto_init() {
	if File_proto_product_product_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_event_proto_rawDesc), len(file_proto_product_product_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_product_product_event_proto_goTypes,
		DependencyIndexes: file_proto_product_product_event_proto_depIdxs,
		MessageInfos:      file_proto_product_product_event_proto_msgTypes,
	}.Build()
	File_proto_product_product_event_proto = out.File
	file_proto_product_product_event_proto_goTypes = nil
	file_proto_product_product_event_proto_depIdxs = nil
}
